! -*- F90 -*-
 BEGIN_PROVIDER [ character*2, symbat, (0:92) ]
BEGIN_DOC
! the periodic table 
END_DOC
      symbat( 0)='XX'
      symbat( 1)=' H'
      symbat( 2)='HE'
      symbat( 3)='LI'
      symbat( 4)='BE'
      symbat( 5)=' B'
      symbat( 6)=' C'
      symbat( 7)=' N'
      symbat( 8)=' O'
      symbat( 9)=' F'
      symbat(10)='NE'
      symbat(11)='NA'
      symbat(12)='MG'
      symbat(13)='AL'
      symbat(14)='SI'
      symbat(15)=' P'
      symbat(16)=' S'
      symbat(17)='CL'
      symbat(18)='AR'
      symbat(19)=' K'
      symbat(20)='CA'
      symbat(21)='SC'
      symbat(22)='TI'
      symbat(23)=' V'
      symbat(24)='CR'
      symbat(25)='MN'
      symbat(26)='FE'
      symbat(27)='CO'
      symbat(28)='NI'
      symbat(29)='CU'
      symbat(30)='ZN'
      symbat(31)='GA'
      symbat(32)='GE'
      symbat(33)='AS'
      symbat(34)='SE'
      symbat(35)='BR'
      symbat(36)='KR'
      symbat(37)='RB'
      symbat(38)='SR'
      symbat(39)=' Y'
      symbat(40)='ZR'
      symbat(41)='NB'
      symbat(42)='MO'
      symbat(43)='TC'
      symbat(44)='RU'
      symbat(45)='RH'
      symbat(46)='PD'
      symbat(47)='AG'
      symbat(48)='CD'
      symbat(49)='IN'
      symbat(50)='SN'
      symbat(51)='SB'
      symbat(52)='TE'
      symbat(53)=' I'
      symbat(54)='XE'
      symbat(55)='CS'
      symbat(56)='BA'
      symbat(57)='LA'
      symbat(58)='CE'
      symbat(59)='PR'
      symbat(60)='ND'
      symbat(61)='PM'
      symbat(62)='SM'
      symbat(63)='EU'
      symbat(64)='GD'
      symbat(65)='TB'
      symbat(66)='DY'
      symbat(67)='HO'
      symbat(68)='ER'
      symbat(69)='TM'
      symbat(70)='YB'
      symbat(71)='LU'
      symbat(72)='HF'
      symbat(73)='TA'
      symbat(74)=' W'
      symbat(75)='RE'
      symbat(76)='OS'
      symbat(77)='IR'
      symbat(78)='PT'
      symbat(79)='AU'
      symbat(80)='HG'
      symbat(81)='TL'
      symbat(82)='PB'
      symbat(83)='BI'
      symbat(84)='PO'
      symbat(85)='AT'
      symbat(86)='RN'
      symbat(87)='FR'
      symbat(88)='RA'
      symbat(89)='AC'
      symbat(90)='TH'
      symbat(91)='PA'
      symbat(92)=' U'
END_PROVIDER

BEGIN_PROVIDER [ character*1, cst, (10) ]
          CST(1)='S'
          CST(2)='P'
          CST(3)='D'
          CST(4)='F'
          CST(5)='G'
          CST(6)='H'
          CST(7)='I'
          CST(8)='J'
          CST(9)='K'
          CST(10)='L'
END_PROVIDER

 BEGIN_PROVIDER [ character*2, shsym, (17) ]
BEGIN_DOC
! names of the orbitals
END_DOC
     shsym(1)='1s'
     shsym(2)='2s'
     shsym(3)='2p'
     shsym(4)='3s'
     shsym(5)='3p'
     shsym(6)='3d'
     shsym(7)='4s'
     shsym(8)='4p'
     shsym(9)='4d'
     shsym(10)='4f'
     shsym(11)='5s'
     shsym(12)='5p'
     shsym(13)='5d'
     shsym(14)='5f'
     shsym(15)='6s'
     shsym(16)='6p'
     shsym(17)='7s'
END_PROVIDER

 BEGIN_PROVIDER [ character*1, cst, (4) ]
BEGIN_DOC
! orbital symmetry
END_DOC
      CST(1)='S'
      cst(2)='P'
      cst(3)='D'
      cst(4)='F'
END_PROVIDER
